language: php
jobs: 
    - stage: unit tests
        script: echo "Running job 1"
    - stage: unit tests
        script: php index.php
    fast_finish: true
    include:
        name: Job 1
        script: echo "Running job 1"
